package com.tongji.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    IDENTIFIER_EXISTS("IDENTIFIER_EXISTS", "账号已存在"),
    IDENTIFIER_NOT_FOUND("IDENTIFIER_NOT_FOUND", "账号不存在"),
    ZGID_EXISTS("ZGID_EXISTS", "知光号已存在"),
    VERIFICATION_RATE_LIMIT("VERIFICATION_RATE_LIMIT", "验证码发送过于频繁"),
    VERIFICATION_DAILY_LIMIT("VERIFICATION_DAILY_LIMIT", "验证码发送次数超限"),
    VERIFICATION_NOT_FOUND("VERIFICATION_NOT_FOUND", "验证码不存在或已过期"),
    VERIFICATION_MISMATCH("VERIFICATION_MISMATCH", "验证码错误"),
    VERIFICATION_TOO_MANY_ATTEMPTS("VERIFICATION_TOO_MANY_ATTEMPTS", "验证码尝试次数过多"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS", "登录凭证错误"),
    PASSWORD_POLICY_VIOLATION("PASSWORD_POLICY_VIOLATION", "密码强度不足"),
    TERMS_NOT_ACCEPTED("TERMS_NOT_ACCEPTED", "请先同意服务条款"),
    REFRESH_TOKEN_INVALID("REFRESH_TOKEN_INVALID", "刷新令牌无效"),
    BAD_REQUEST("BAD_REQUEST", "请求参数错误"),
    WALLET_NOT_FOUND("WALLET_NOT_FOUND", "钱包不存在"),
    WALLET_BALANCE_NOT_ENOUGH("WALLET_BALANCE_NOT_ENOUGH", "余额不足"),
    WALLET_HELD_BALANCE_NOT_ENOUGH("WALLET_HELD_BALANCE_NOT_ENOUGH", "冻结余额不足"),
    WALLET_ESCROW_BALANCE_NOT_ENOUGH("WALLET_ESCROW_BALANCE_NOT_ENOUGH", "托管余额不足"),
    WALLET_DUPLICATE_BUSINESS_REF("WALLET_DUPLICATE_BUSINESS_REF", "账务请求重复"),
    ESCROW_NOT_FOUND("ESCROW_NOT_FOUND", "托管单不存在"),
    ESCROW_INVALID_STATUS("ESCROW_INVALID_STATUS", "托管单状态不合法"),
    PROMOTION_CAMPAIGN_NOT_FOUND("PROMOTION_CAMPAIGN_NOT_FOUND", "推广活动不存在"),
    PROMOTION_BID_DUPLICATE("PROMOTION_BID_DUPLICATE", "推广出价已存在"),
    PROMOTION_BID_WINDOW_CLOSED("PROMOTION_BID_WINDOW_CLOSED", "竞价窗口已关闭"),
    PROMOTION_BID_ESCROW_REQUIRED("PROMOTION_BID_ESCROW_REQUIRED", "请先授权推广竞价保证金"),
    PROMOTION_BID_INVALID_RESOURCE("PROMOTION_BID_INVALID_RESOURCE", "推广资源类型不合法"),
    PROMOTION_ALLOCATION_NOT_FOUND("PROMOTION_ALLOCATION_NOT_FOUND", "推广位分配不存在"),
    PROMOTION_SETTLEMENT_INVALID_STATUS("PROMOTION_SETTLEMENT_INVALID_STATUS", "推广结算状态不合法"),
    INTERNAL_ERROR("INTERNAL_ERROR", "服务器内部错误");

    private final String code;
    private final String defaultMessage;

    ErrorCode(String code, String defaultMessage) {
        this.code = code;
        this.defaultMessage = defaultMessage;
    }
}
